sudo: required
services:
  - docker
install:
  - docker build -t xchem/opentrons .
script:
  - docker run xchem/opentrons /bin/sh -c "cd /usr/local/opentrons && xchem_ot/tests/test_scripts/test_all_scripts.sh && nosetests"
